name: Keep Apps Alive

on:
  workflow_dispatch:  # Solo ejecución manual

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Wake up apps
        run: python wake_up.py